options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _SERVICE: calculate-materials
  _REGION: us-east4
  _REPO: roofing
steps:
- name: gcr.io/cloud-builders/docker
  args: ['build','-t','-docker.pkg.dev/\roofingcalculator//:\','.']
  dir: calculate_materials
- name: gcr.io/cloud-builders/docker
  args: ['push','-docker.pkg.dev/\roofingcalculator//:\']
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args: ['run','deploy','',
         '--image','-docker.pkg.dev/\roofingcalculator//:\',
         '--region','','--allow-unauthenticated','--platform','managed','--port','8080']
images:
- '-docker.pkg.dev/\roofingcalculator//:\'