options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _SERVICE: calculate-materials
  _REGION: us-east4
  _REPO: roofing

steps:
# Build the image from the calculate_materials folder
- name: gcr.io/cloud-builders/docker
  args: ['build','-t','${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$SHORT_SHA','.']
  dir: calculate_materials

# Push the image to Artifact Registry
- name: gcr.io/cloud-builders/docker
  args: ['push','${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$SHORT_SHA']

# Deploy to Cloud Run (public)
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args:
    ['run','deploy','${_SERVICE}',
     '--image','${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$SHORT_SHA',
     '--region','${_REGION}','--platform','managed','--allow-unauthenticated','--port','8080']

images:
- '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$SHORT_SHA'